- name: Clone ComposeFile
  shell: git clone https://github.com/R4yl1n/setUpReverseProxy.git
  ignore_errors: true

- name: fetch updates
  shell: |
    git fetch origin
    git pull
  args:
    chdir: setUpReverseProxy/

- name: Install Docker Compose manually
  shell: |
    DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
    mkdir -p $DOCKER_CONFIG/cli-plugins
    curl -SL https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
    sudo chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

- name: Run Compose file
  shell: docker compose up -d
  args:
    chdir: setUpReverseProxy/ComposeFile
