- name: Clone ComposeFile
  shell: git clone https://github.com/R4yl1n/setUpReverseProxy.git
  ignore_errors: true

- name: fetch updates
  shell: |
    git fetch origin
    git pull
  args:
    chdir: setUpReverseProxy/

- name: Run Compose file
  shell: docker compose up -d
  args:
    chdir: setUpReverseProxy/ComposeFile
