- name: setupReverseProxy
  hosts: linux
  become: yes
  remote_user: ubuntu

  vars: 
    varReboot: false
    varCompose_Manual_Installation: false #onetime Installation but manualy
    varCompose_apt_installation: true #enable this one if you want to install compose via apt
    varStart_Compose: true #set true to install/Update and run the Compose
    varStop_Compose: false #set true to stop the docker compose

  pre_tasks:
    - name: install necessary packages
      apt:
        name: 
          - docker.io
          - git
          - curl
        state: latest

    - name: install docker compose
      apt:
        update_cache: yes
        name:
          - docker-compose
        state: latest
      when: varCompose_apt_installation is defined and varCompose_apt_installation

  roles:
    - {role: BootContainers, when: varStart_Compose is defined and varStart_Compose}
    - {role: StopCompose, when: varStop_Compose is defined and varStop_Compose}
    - {role: InstallComposeManualy, when: varStop_Compose is defined and varStop_Compose}

  post_tasks:
    - name: reboot all hosts
      reboot:
      when: varReboot is defined and varReboot

