- name: setupReverseProxy
  hosts: linux
  become: yes
  remote_user: ubuntu

  vars: 
    varReboot: false
    varCompose_apt_installation: false #enable this one if you want to install compose via apt

  pre_tasks:
    - name: install necessary packages
      apt:
        name: 
          - docker.io
          - git
        state: latest

    - name: install docker compose
      apt:
        name:
          - docker-compose-plugin
        state: latest
      when: varCompose_apt_installation is defined and varCompose_apt_installation

  roles:
    - BootContainers

  post_tasks:
    - name: reboot all hosts
      reboot:
      when: varReboot is defined and varReboot

