version: "3.3"

services:
  nginx_no_cache:
    build: ./nginx_no_cache/
    restart: always
    container_name: nginx_no_cache
    ports: 
      - 8080:80

  
  nginx_with_cache:
    build: ./nginx_with_cache/
    restart: always
    container_name: nginx_with_cache
    ports:
      - 80:80


  apache:
    image: httpd
    container_name: apache